apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Release.Namespace }}
data:
  grafana.ini: |
{{ .Values.grafana.config.grafanaIni | indent 4 }}
  provisioning-datasources-loki.yaml: |
{{ tpl .Values.grafana.config.datasource . | indent 4 }}
