apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Values.namespace }}
data:
  grafana.ini: |
{{ .Values.grafana.config.grafanaIni | indent 4 }}
  provisioning-datasources-loki.yaml: |
{{ .Values.grafana.config.datasource | indent 4 }}
