apiVersion: v1
kind: Service
metadata:
  name: deploy-one-svc
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
    prometheus.io/path: {{ .Values.prometheus.path }}
  labels:
    app: deploy-one
spec:
  selector:
    app: {{ include "deploy-one-chart.fullname" . }}
  ports:
    - port: 9100
      targetPort: 9100
