apiVersion: v1
kind: Service
metadata:
  name: deploy-two-svc
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}  
  labels:
    app: deploy-two
spec:
  selector:
    app: {{ include "deploy-two-chart.fullname" . }}
  ports:
    - port: 9100
      targetPort: 9100
