apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Name }}
    spec:
      serviceAccountName: {{ .Values.saName }}
      containers:
        - name: {{ .Values.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config.file=/etc/prometheus/config/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.enable-lifecycle
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
          {{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
      volumes:
        {{- range .Values.volumes }}
          - name: {{ .name }}
            {{- if eq .type "emptyDir" }}
            emptyDir: {}
            {{- else if eq .type "configMap" }}
            configMap:
              name: {{ .configMapName }}
            {{- end }}
        {{- end }}
