apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: 100
  port:
    targetPort: {{ .Values.service.targetPort }}
#  tls:
#    termination: {{ .Values.route.tls.termination | quote }}
#    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecurePolicy | quote }}
#  wildcardPolicy: None